version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
